####################################################################################################
#
# ANSI Codes
#
#   RESET \033[0m
#   COLOR \033[1;%dm
#   BOLD  \033[1m
#
####################################################################################################

version: 1

####################################################################################################

formatters:

  simple:
    format: '%(asctime)s - %(name)s - %(module)s.%(levelname)s - %(message)s'

  ansi:
    format: '<ESC>[1;32m%(asctime)s<ESC>[0m - <ESC>[1;34m%(name)s.%(funcName)s<ESC>[0m - <ESC>[1;31m%(levelname)s<ESC>[0m - %(message)s'

####################################################################################################

handlers:

  console:
    class: logging.StreamHandler
    # level: INFO
    # formatter: ansi
    stream: ext://sys.stdout

####################################################################################################

# PySpice.Doc.ExampleTools.find_libraries
root:
  # level: CRITICAL
  # level: ERROR
  level: WARNING
  # level: INFO
  # level: DEBUG
  handlers: [console]

####################################################################################################

loggers:

  PySpice:
    # level: DEBUG
    level: INFO
    # level: WARNING
